### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "email": "user@1234.com",
    "password": "test1234"
}

###
POST {{url}}/auth/login/

{
    "email": "user@1234.com",
    "password": "test1234"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

###

#PUT {{url}}/hotels/3
#Content-Type: application/json
#Accept: application/json
#Authorization: Bearer {{jwt_token}}
#
#{
#  "hotelName": "Ritz Carlton",
#  "hotelAddress": "London City",
#  "hotelType": "LUXURY"
#}

###

#DELETE {{url}}/hotels/5

###
